### SITES
GET http://localhost:5000/

### REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "test22",
    "email": "test22@gmail.com",
    "password": "123456"
}

### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "rum123@gmail.com",
    "password": "123456"
}

### LOGOUT
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoicnVtdHFuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE2ODg5MDk0MjQsImV4cCI6MTcyMDQ2NzAyNH0.BsPJsf_glewW9XCGBQJ7ZMrmp-QMPpakH89KrI-deZ4"
}

### REFRESH TOKEN
POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoicnVtdHFuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE2ODg5MDk0MjQsImV4cCI6MTcyMDQ2NzAyNH0.BsPJsf_glewW9XCGBQJ7ZMrmp-QMPpakH89KrI-deZ4"
}

### GET LIST USER BY ADMIN
GET http://localhost:5000/auth/admin/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoicnVtdHFuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE2ODg5MDk0MjQsImV4cCI6MTY4ODkwOTQ4NH0.0yH5HPPubjzlprw394x5AMWVp8SkHpbavl9_rx04E3k
