### SITES
GET http://localhost:5000/

### REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "test22",
    "email": "test22@gmail.com",
    "password": "123456"
}

### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "rum123@gmail.com",
    "password": "123456"
}

### LOGOUT
POST http://localhost:5000/api/auth/logout

### GET LIST USER BY ADMIN
GET http://localhost:5000/auth/admin/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMGExMGJiMDNhN2NiMzRjNzhiMjIiLCJuYW1lIjoidGVzdDIyIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE2ODg4NzIyMzIsImV4cCI6MTY4ODg3MjI0Mn0.dO_FKcQyYaSUvBl2r8S4vK9m9Kj1lTAk1JKuWhGyJE8
