### SITES
GET http://localhost:5000/

### REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "drhappykun",
    "email": "drhappykun.tqn@gmail.com",
    "password": "123456"
}

### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "drhappykun.tqn@gmail.com",
    "password": "Pu@owH4s"
}

### LOGOUT
DELETE http://localhost:5000/api/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGMxNDlkNmZiMTY0NDFlYjgwZDNmOTgiLCJuYW1lIjoiTmd1ecOqbiBUcuG6p24gUXXhu5FjIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE2OTAzODg5ODQsImV4cCI6MTcyMTk0NjU4NH0.IDimZ_L1XRYOnUDzIEvPM8JcWIbEgSgqtCWojm0YO4g"
}

### REFRESH TOKEN
POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4OTA0MTY1MiwiZXhwIjoxNzIwNTk5MjUyfQ.TM7stHGBueYhyNjjUH0bMVDKwv1wxAVns-tysO3E04k"
}

### GET LIST USER BY ADMIN
GET http://localhost:5000/auth/admin/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MDM4OTU5NSwiZXhwIjoxNjkwMzkzMTk1fQ.MfFUtH-5KinZujfSICunqSy51gQQy_HhwWI7bD8lb_0

### CREATE USER BY ADMIN
POST http://localhost:5000/auth/admin/user/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MDM4OTU5NSwiZXhwIjoxNjkwMzkzMTk1fQ.MfFUtH-5KinZujfSICunqSy51gQQy_HhwWI7bD8lb_0

{
    "name": "abcd123456",
    "email": "abcd123456@gmail.com",
    "password": "123456",
    "role": "regular"
}

### SOFT DELETE USER BY ADMIN
DELETE http://localhost:5000/auth/admin/user/soft-delete-user/64c150bb16a1b71130fef73e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MDM4OTU5NSwiZXhwIjoxNjkwMzkzMTk1fQ.MfFUtH-5KinZujfSICunqSy51gQQy_HhwWI7bD8lb_0

### GET LIST DELETED USERS BY ADMIN
GET http://localhost:5000/auth/admin/user/trash-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MDM4OTU5NSwiZXhwIjoxNjkwMzkzMTk1fQ.MfFUtH-5KinZujfSICunqSy51gQQy_HhwWI7bD8lb_0

### RESTORE USER BY ADMIN
PATCH http://localhost:5000/auth/admin/user/restore-user/64c150bb16a1b71130fef73e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MDM4OTU5NSwiZXhwIjoxNjkwMzkzMTk1fQ.MfFUtH-5KinZujfSICunqSy51gQQy_HhwWI7bD8lb_0

### DESTROY USER BY ADMIN
DELETE http://localhost:5000/auth/admin/user/destroy-user/64c150bb16a1b71130fef73e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGFhMTBiYWNjZTc5YTllOTU1Y2NhM2EiLCJuYW1lIjoiQWRtaW5pc3RyYXRvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MDM4OTU5NSwiZXhwIjoxNjkwMzkzMTk1fQ.MfFUtH-5KinZujfSICunqSy51gQQy_HhwWI7bD8lb_0




### AUTH GOOGLE
POST http://localhost:5000/api/auth/google
Content-Type: application/json

{
    "access_token": "ya29.a0AbVbY6NqQ9ftUXoMAPdDeKdFTRklAbHihshVoGVD1cPYc50MCMLUdc8XHoH_DZLZNzzL4w73K5fe5bsX3xFyKYnFBddeaRDeelbGaceZ6l_dkCD7AgSpGmPdSSK2m500lLV-KhnSotp9Eb6BJkoF8Drb58UCaCgYKAVQSARASFQFWKvPl3DoJVBFCn_ewfoLcZC8CKw0163"
}

###
POST http://localhost:5000/api/auth/forgot-password
Content-Type: application/json

{
    "email": "drhappykun.tqn@gmail.com"
}